services:
  - type: web
    name: mc-irc-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: HTTP_PORT
        value: 10000
      - key: IRC_PORT
        value: 6667
      - key: SERVER_NAME
        value: mc-irc-render
      - key: DEFAULT_CHANNEL
        value: "#minecraft"
